export const SET_VIDEOS = 'SET_VIDEOS';
export const SET_MODAL = 'SET_MODAL';
export const SET_IS_URL = 'SET_IS_URL';
export const SET_SELECTED_VIDEO = 'SET_SELECTED_VIDEO';
export const SET_SELECTED_VIDEOS = 'SET_SELECTED_VIDEOS';
export const REMOVE_SELECTED_VIDEO = 'REMOVE_SELECTED_VIDEO';
export const SET_VIDEOS_FILTER = 'SET_VIDEOS_FILTER';
export const SET_VIDEO_STATUS = 'SET_VIDEO_STATUS';
